# GitHub Actions 워크플로우 이름 지정
name: 린트 검사하기

on: [push]

jobs:
  yumemi-lint:
    name: Lint 검사
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      # Flutter 환경 설정
      - name: Flutter 설정
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"

      # 의존성 설치
      - name: 의존성 설치
        run: flutter pub get

      # 빌드러너 실행
      #      - name: 빌드러너 실행
      #        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Flutter 로컬라이즈 파일 생성
      #      - name: 로컬라이즈 파일 생성
      #        run: flutter gen-l10n

      # .env 파일 생성
      #      - name: .env 파일 생성
      #        run: |
      #          touch .env
      #          echo "BASE_TEST_URL=yourBaseTestURL" >> .env
      #          echo "IMAGE_BASE_URL=yourImageBaseURL" >> .env

      # Flutter 코드 분석 실행
      # --no-fatal-infos 옵션은 정보 메시지를 에러로 처리하지 않도록 설정
      - name: Flutter Lint 실행
        run: flutter analyze --no-fatal-infos
